# SUSE Entities Ruby hash
'&exampleuser;' => '{tux}',
'&exampleuserII;' => '{wilber}',
'&examplegroup;' => '{users}',
'&rootuser;' => '{<systemitem xmlns='http://docbook.org/ns/docbook' class='username'>root</systemitem>}',
'&grub;' => '{GRUB}',
'&suse;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE</phrase>}',
'&novell;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>Novell</phrase>}',
'&x86;' => '{x86}',
'&amd64;' => '{AMD64}',
'&zseries;' => '{z&nbsp;Systems}',
'&zsystems;' => '{z Systems}',
'&ipf;' => '{Itanium}',
'&ipseries;' => '{POWER}',
'&ppc;' => '{POWER}',
'&power;' => '{POWER}',
'&ppc64le;' => '{ppc64le}',
'&intel64;' => '{Intel&nbsp;64}',
'&x86-64;' => '{&amd64;/&intel64;}',
'&arm;' => '{ARM}',
'&aarch64;' => '{AArch64}',
'&arm64;' => '{&arm;&nbsp;&aarch64;}',
'&suselinux;' => '{&suse; Linux}',
'&yast;' => '{YaST}',
'&yastcc;' => '{&yast; Control Center}',
'&ay;' => '{AutoYaST}',
'&openscap;' => '{OpenSCAP}',
'&deploy;' => '{Deployment Guide}',
'&slea;' => '{SLE}',
'&slsa;' => '{SLES}',
'&sls;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise Server</phrase>}',
'&sle;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise</phrase>}',
'&sled;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise Desktop</phrase>}',
'&productname;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Manager</phrase>}',
'&productnumber;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>3.2</phrase>}',
'&productnumber3;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>3</phrase>}',
'&sdk;' => '{SUSE Software Development Kit}',
'&ncc;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>Novell Customer Center</phrase>}',
'&scc;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Customer Center</phrase>}',
'&susemgr;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>&suse; Manager</phrase>}',
'&susemgrdb;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>&suse; Manager with Database</phrase>}',
'&susemgrproxy;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>&susemgr; Proxy</phrase>}',
'&mgrquick;' => '{Quick Start}',
'&mgrproxyquick;' => '{Proxy Quick Start}',
'&slereg;' => '{SUSE&reg; Linux Enterprise}',
'&susemgrreg;' => '{&suse;&reg; Manager}',
'&thrdmrk;' => '{*}',
'&kiwi;' => '{KIWI}',
'&kickstart;' => '{Kickstart}',
'&smtool;' => '{Subscription Management Tool}',
'&smt;' => '{SMT}',
'&xen;' => '{Xen}',
'&xenreg;' => '{Xen&reg;}',
'&kvm;' => '{KVM}',
'&vmhost;' => '{VM Host Server}',
'&vmguest;' => '{VM Guest}',
'&susestudio;' => '{&suse; Studio}',
'&prompt.root;' => '{<prompt xmlns='http://docbook.org/ns/docbook'>root # </prompt>}',
'&prompt.user;' => '{<prompt xmlns='http://docbook.org/ns/docbook'>&exampleuser; &gt; </prompt>}',
'&prompt.user2;' => '{<prompt xmlns='http://docbook.org/ns/docbook'>&exampleuserII; &gt; </prompt>}',
'&euro;' => '{&#x20AC;}',
#network entities
'&exampledomain;' => '{example.com}',
'&exampledomain1;' => '{example.net}',
'&exampledomain2;' => '{example.org}',
'&subnetI;' => '{192.168.1}',
'&subnetImask;' => '{&subnetI;.0/24}',
'&subnetII;' => '{192.168.2}',
'&subnetIImask;' => '{&subnetII;.0/24}',
'&subnetIII;' => '{192.168.3}',
'&subnetIIImask;' => '{&subnetIII;.0/24}',
'&subnetIV;' => '{192.168.4}',
'&subnetIVmask;' => '{&subnetIV;.0/24}',
'&subnetV;' => '{192.168.5}',
'&subnetVmask;' => '{&subnetV;.0/30}',
'&subnetnat;' => '{192.168.100}',
'&subnetnatmask;' => '{&subnetnat;.0/24}',
'&subnetv6;' => '{2002:c0a8}',
'&subnetIbc;' => '{&subnetI;.255}',
'&subnetIIbc;' => '{&subnetII;.255}',
'&subnetIIIbc;' => '{&subnetIII;.255}',
'&subnetIVbc;' => '{&subnetIV;.255}',
'&subnetVbc;' => '{&subnetV;.252}',
'&subnetmask;' => '{255.255.255.0}',
'&smbname;' => '{smb.&exampledomain;}',
'&nfsname;' => '{nfs.&exampledomain;}',
'&iscsiname;' => '{iscsi.&exampledomain;}',
'&proxyname;' => '{www-proxy.&exampledomain;}',
'&ldapname;' => '{ldap.&exampledomain;}',
'&nisname;' => '{nis.&exampledomain;}',
'&slpname;' => '{slp.&exampledomain;}',
'&ntpname;' => '{ntp.&exampledomain;}',
'&tftpname;' => '{tftp.&exampledomain;}',
'&pxename;' => '{pxe.&exampledomain;}',
'&kdcname;' => '{kdc.&exampledomain;}',
'&dnsname;' => '{dns.&exampledomain;}',
'&dhcpname;' => '{dhcp.&exampledomain;}',
'&cupsname;' => '{cups.&exampledomain;}',
'&wwwname;' => '{www.&exampledomain;}',
'&wwwname1;' => '{www.&exampledomain1;}',
'&wwwname2;' => '{www.&exampledomain2;}',
'&ftpname;' => '{ftp.&exampledomain;}',
'&mailname;' => '{mail.&exampledomain;}',
'&routerextname;' => '{routerext.&exampledomain;}',
'&routerintname;' => '{routerint.&exampledomain;}',
'&fwextname;' => '{fwext.&exampledomain;}',
'&fwintname;' => '{fwint.&exampledomain;}',
'&gatename;' => '{gate.&exampledomain;}',
'&wsIname;' => '{jupiter.&exampledomain;}',
'&wsIIname;' => '{venus.&exampledomain;}',
'&wsIIIname;' => '{saturn.&exampledomain;}',
'&wsIVname;' => '{mercury.&exampledomain;}',
'&wsI;' => '{jupiter}',
'&wsII;' => '{venus}',
'&wsIII;' => '{saturn}',
'&wsIV;' => '{mercury}',
'&xenhostname;' => '{earth.&exampledomain;}',
'&xenhost;' => '{earth}',
'&xenhostip;' => '{&subnetI;.20}',
'&xenguestname;' => '{alice.&exampledomain;}',
'&xenguest;' => '{alice}',
'&xenguestip;' => '{&subnetI;.21}',
'&xennatguest;' => '{dolly}',
'&xennatip;' => '{&subnetnat;.1}',
'&wsImac;' => '{00:30:6E:08:EC:80}',
'&wsIImac;' => '{00:00:1C:B5:A4:32}',
'&wsIIImac;' => '{00:17:31:CA:A3:4A}',
'&wsIVmac;' => '{00:16:35:AF:94:4B}',
'&smbip;' => '{&subnetI;.110}',
'&smbipv6;' => '{&subnetv6;:16e::}',
'&nfsip;' => '{&subnetI;.110}',
'&nfsipv6;' => '{&subnetv6;:16e::}',
'&iscsiip;' => '{&subnetI;.111}',
'&iscsiipv6;' => '{&subnetv6;:16f::}',
'&proxyip;' => '{&subnetI;.112}',
'&proxyipv6;' => '{&subnetv6;170::}',
'&ldapip;' => '{&subnetI;.113}',
'&ldapipv6;' => '{&subnetv6;:171::}',
'&nisip;' => '{&subnetI;.113}',
'&nisipv6;' => '{&subnetv6;:171::}',
'&ntpip;' => '{&subnetI;.116}',
'&ntpipv6;' => '{&subnetv6;:174::}',
'&tftpip;' => '{&subnetI;.115}',
'&tftpipv6;' => '{&subnetv6;:173::}',
'&pxeip;' => '{&subnetI;.115}',
'&pxeipv6;' => '{&subnetv6;:173::}',
'&kdcip;' => '{&subnetI;.114}',
'&kdcipv6;' => '{&subnetv6;:172::}',
'&dnsip;' => '{&subnetI;.116}',
'&dnsipv6;' => '{&subnetv6;:174::}',
'&vpnip;' => '{&subnetI;.120}',
'&slpip;' => '{&subnetII;.254}',
'&slpipv6;' => '{&subnetv6;:2fe::}',
'&dhcpip;' => '{&subnetII;.254}',
'&dhcpipv6;' => '{&subnetv6;:2fe::}',
'&cupsip;' => '{&subnetII;.253}',
'&cupsipv6;' => '{&subnetv6;:2fd::}',
'&routerintipI;' => '{&subnetI;.1}',
'&routerintipIv6;' => '{&subnetv6;:101::}',
'&fwintipI;' => '{&subnetI;.1}',
'&fwintipIv6;' => '{&subnetv6;:101::}',
'&routerintipII;' => '{&subnetII;.1}',
'&routerintipIIv6;' => '{&subnetv6;:201::}',
'&fwintipII;' => '{&subnetII;.1}',
'&fwintipIIv6;' => '{&subnetv6;:201::}',
'&wwwip;' => '{&subnetIII;.100}',
'&wwwipv6;' => '{&subnetv6;:364::}',
'&wwwip1;' => '{&subnetIII;.101}',
'&wwwip1v6;' => '{&subnetv6;:365::}',
'&wwwip2;' => '{&subnetIII;.102}',
'&wwwip2v6;' => '{&subnetv6;:366::}',
'&ftpip;' => '{&subnetIII;.105}',
'&ftpipv6;' => '{&subnetv6;:369::}',
'&mailip;' => '{&subnetIII;.108}',
'&mailipv6;' => '{&subnetv6;:36c::}',
'&routerextipIII;' => '{&subnetIII;.2}',
'&routerextipIIIv6;' => '{&subnetv6;:302::}',
'&fwextipIII;' => '{&subnetIII;.2}',
'&fwextipIIIv6;' => '{&subnetv6;:302::}',
'&routerintipIV;' => '{&subnetIV;.1}',
'&routerintipIVv6;' => '{&subnetv6;:401::}',
'&routerextipIV;' => '{&subnetIV;.2}',
'&routerextipIVv6;' => '{&subnetv6;:402::}',
'&fwextipIV;' => '{&subnetIV;.2}',
'&fwextipIVv6;' => '{&subnetv6;:402::}',
'&fwintipIV;' => '{&subnetIV;.1}',
'&fwintipIVv6;' => '{&subnetv6;:401::}',
'&routerextipV;' => '{&subnetV;.2}',
'&routerextipVv6;' => '{&subnetv6;:502::}',
'&fwextipV;' => '{&subnetV;.2}',
'&fwextipVv6;' => '{&subnetv6;:502::}',
'&gateip;' => '{&subnetV;.1}',
'&gateipv6;' => '{&subnetv6;:501::}',
'&wsIip;' => '{&subnetII;.100}',
'&wsIipv6;' => '{&subnetv6;:264::}',
'&wsIIip;' => '{&subnetII;.101}',
'&wsIIipv6;' => '{&subnetv6;:265::}',
'&wsIIIip;' => '{&subnetII;.102}',
'&wsIIIipv6;' => '{&subnetv6;:266::}',
'&wsIVip;' => '{&subnetII;.103}',
'&wsIVipv6;' => '{&subnetv6;:267::}',
'&vpnclient1;' => '{&subnetII;.110}',
'&vpnclient2;' => '{&subnetII;.111}',
# SUSE Manager Entities
'&mgrinstguide;' => '{Installation &amp; Troubleshooting Guide}',
'&mgrclientconfguide;' => '{Client Configuration Guide}',
'&mgrrefguide;' => '{Reference Guide}',
'&mgruserguide;' => '{User Guide}',
'&mgrquick;' => '{Quick Start}',
'&mgrproxyquick;' => '{Proxy Quick Start}',
'&mgrgetstart;' => '{<citetitle xmlns='http://docbook.org/ns/docbook'>Getting Started Guide</citetitle>}',
'&mgrrefguide;' => '{<citetitle xmlns='http://docbook.org/ns/docbook'>Reference Guide</citetitle>}',
'&mgrbestpract;' => '{<citetitle xmlns='http://docbook.org/ns/docbook'>Best Practices Guide</citetitle>}',
'&mgruserguide;' => '{<citetitle xmlns='http://docbook.org/ns/docbook'>User Guide</citetitle>}',
'&mgradvtop;' => '{<citetitle xmlns='http://docbook.org/ns/docbook'>Advanced Topics Guide</citetitle>}',
'&sles-version;' => '{12}',
'&sp-version;' => '{SP3}',
'&sp-ver;' => '{3}',
'&rh;' => '{Red Hat}',
'&rhn;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>Red Hat Network</phrase>}',
'&rhna;' => '{RHN}',
'&updagent;' => '{Red Hat Update Agent}',
'&rhnregcl;' => '{RHN Registration Client}',
'&up2date;' => '{up2date}',
'&proxy;' => '{Proxy Server}',
'&rhel;' => '{<phrase xmlns='http://docbook.org/ns/docbook'>Red Hat Enterprise Linux</phrase>}',
'&rhela;' => '{RHEL}',
'&rhnwebsite;' => '{rhn.redhat.com}',
'&intersatsync;' => '{Inter-Satellite Sync}',
'&rhnsatsync;' => '{RHN Satellite Synchronization}',
'&rhnsatact;' => '{RHN Satellite Activate }',
'&rhnsatexp;' => '{RHN Satellite Exporter}',
'&mgrd;' => '{&susemanager; daemon}',
'&webui;' => '{Web&nbsp;UI}',
'&cmdrhnreg;' => '{rhn_register}',
'&cmdactkey;' => '{rhnreg_ks}',
'&cmdsatact;' => '{rhn-satellite-activate}',
'&cmdsatexp;' => '{rhn-satellite-exporter}',
'&cmdspacereport;' => '{spacewalk-report}',
'&cmdrhnsat;' => '{rhn-satellite}',
'&cmdsearch;' => '{rhn-search}',
'&rhnupgr;' => '{rhn-upgrade}',
'&rhnsattools;' => '{rhns-satellite-tools}',


